# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 30 Days of Habit
email: hi@chrislarson.me
description: >
  Forming a daily habit of writing
logo: "/img/profile.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chrislarson.me" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Chris Larson'
bio: >
  September is my birthday month. This year I'm doing something special for myself. I'm giving my future 40 year old self a birthday present.
author_image: "/img/profile.jpg"
twitter_username: chrylarson
github_username:  chrylarson

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
